### ISSUE TITLE
Suggestion: Ability to fetch parent & child in edit post

### ISSUE THREAD

**Issue by moxet** [ihslimn/jet-form-builder-update-field#1] opened 2023-07-16 11:47 UTC
I've tried the add-on and it works perfect as explained in tutorial.

I have a suggestion to add support for edit CPT form, it doe'snt fetch child element which was selected in adding CPT form.

Regards

**Comment by ihslimn** [comment] 2023-07-16 12:04
do you mean loading values on form load?

**Comment by ihslimn** [comment] 2023-07-16 13:00
I suppose you meant exactly that :)
please, check updated version and let me know it works as you need

**Comment by moxet** [comment] 2023-07-16 13:02
Yes exactly! Load values in form preset. It actually fetch the parent value
but not child checkboxes.

**Comment by ihslimn** [comment] 2023-07-17 19:45
as I mentioned - you may download a new version, it works as you need
I close this issue as resolved

**Closed by ihslimn** 2023-07-17 19:45 UTC
Labels: enhancement

**Comment by moxet** [comment] 2023-07-18 14:15
Hi @ihslimn i used the updated code, it has same issue if you want to see. Support might have shared the logins of healthcare directory. Form name is edit_doctor

**Comment by ihslimn** [comment] 2023-07-18 15:04
https://prnt.sc/lt-PEgNNkTsq you just forgot to enable the option in the field

I enabled it now, please, check here /my-account/edit-doctor/?_doctor_id=2454 for example - specialty level two will get options upon page load (have not included your site base into URL provided you do not want to share it publicly; basically try editing "Aber Jan" doctor with the form)

**Comment by moxet** [comment] 2023-07-18 16:16
Let me share my details, please check this loom video
https://www.loom.com/share/c298e112f9bf4f339f36d92b237ac4ae

**Comment by ihslimn** [comment] 2023-07-18 16:45
The bug with choosing values is indeed peculiar :) I'll check it late, thank you for reporting it!

Also, you mentioned that Speciality field is not pulling top-level terms - it is just that you had it set not to Generate Dynamically, but to Terms https://prnt.sc/-bl9JTGJO5UA
Now it pulls terms correctly (but it is not presetting value as you expect it to, and I will explain why)

You need a special type of preset - preset top-level term - in this case. It is not a bug report (and also not of this addon), but rather a request for the functionality of JetFormBuilder. Currently, when presetting terms it just takes some term, that may be or may be not among top-level terms.
I'll see if some workaround could be used in this case, or maybe it is something that could be changed in JetFormBuilder code.

My name is "Mykhailo" and it is pronounced a bit like Me - Hi - Law, with the stress on Hi :)
Any way it is just an interesting fact you may want to know
Everybody calls me Misha in real life, and I'm fine with that :)

**Comment by moxet** [comment] 2023-07-19 06:25
Thank you for the detailed answer Misha.

I did change the source to terms & it fetched the parent terms but i was having concern of child terms. For now i will try to show them in static checkboxes it works as its edit page not add page so we can somehow manage it.

I will appreciate if this functionality is extended to be used in future. 

We can close this issue here, if you found time or plan to implement this feature, please let me know.

Best Regards

**Comment by ihslimn** [comment] 2023-07-20 10:37
@moxet 
girafffee has updated JetFormbuilder 3.1 with a fix
please, download a new version of JetFormBuilder, the bug with checking values of updated field should be gone

**Comment by moxet** [comment] 2023-07-20 11:19
Hello Misha, 

I am already using 3.1.0.4 but the bug is still there. Please point out if there is any other place from where i can download the updated version.

As for values loading, i somehow manage to fetch and show it with SQL Query + AutoComplete feature as seen below, the only issue now is pre-set values.

![Screenshot_15](https://github.com/ihslimn/jet-form-builder-update-field/assets/919409/bffd1f2d-10c9-4100-b153-a1ff26012fb8)

**Comment by ihslimn** [comment] 2023-07-20 12:08
https://github.com/Crocoblock/jetformbuilder/tree/3.1.0
https://prnt.sc/2-7cK0Cfdh0k
here

**Comment by moxet** [comment] 2023-07-20 12:21
Fatal error: Cannot redeclare jet_form_builder_init() (previously declared in /home/1001093.cloudwaysapps.com/nfscargaer/public_html/wp-content/plugins/jetformbuilder/jet-form-builder.php:22) in /home/1001093.cloudwaysapps.com/nfscargaer/public_html/wp-content/plugins/jetformbuilder-3.1.0/jet-form-builder.php on line 30

**Comment by moxet** [comment] 2023-07-31 13:26
Hey @ihslimn can we get any updates on the checkbox values not set by default? I almost completed everything except this option

![Screenshot_2](https://github.com/ihslimn/jet-form-builder-update-field/assets/919409/48573f41-9ecf-4a66-89d3-8c6c2f8ed51f)

**Comment by moxet** [comment] 2023-07-31 13:34
It was'nt selecting the preset values, which somehow i resolved with query builder + terms etc. Now it shows parent terms select but child are'nt. Same website if you want to login. Dashboard > Hospital > Edit > Cleveland Clinic Abu Dhabi
